// Generated by tools/build.mjs. Do not edit.
// Sources: brand/kasseneck-logo.svg, brand/animations.json.
import type { Animation } from "./types.js";

export type LogoPart = "frame" | "corner";
export interface LogoCell { index: number; row: number; col: number; part: LogoPart }
export interface LogoGlyph { char: string; bbox: { x: number; y: number; width: number; height: number }; d: string }

/** Box of the brand file the geometry lives in. */
export const LOGO_WIDTH = 332;
export const LOGO_HEIGHT = 48;
/** The mark: 8×8 cells of 6 units. */
export const GRID = 8;
export const UNIT = 6;

/** The open frame (two paths) and the filled corner — the brand paths, byte for byte. */
export const FRAME_PATHS = ["M0 0H48V30H42V6H0Z","M0 6V48H30V42H6V6Z"] as const;
export const CORNER_PATH = "M30 30H48V48H30Z";

export const cells: readonly LogoCell[] = [
  { index: 0, row: 0, col: 0, part: "frame" },
  { index: 1, row: 0, col: 1, part: "frame" },
  { index: 2, row: 0, col: 2, part: "frame" },
  { index: 3, row: 0, col: 3, part: "frame" },
  { index: 4, row: 0, col: 4, part: "frame" },
  { index: 5, row: 0, col: 5, part: "frame" },
  { index: 6, row: 0, col: 6, part: "frame" },
  { index: 7, row: 0, col: 7, part: "frame" },
  { index: 8, row: 1, col: 0, part: "frame" },
  { index: 9, row: 1, col: 7, part: "frame" },
  { index: 10, row: 2, col: 0, part: "frame" },
  { index: 11, row: 2, col: 7, part: "frame" },
  { index: 12, row: 3, col: 0, part: "frame" },
  { index: 13, row: 3, col: 7, part: "frame" },
  { index: 14, row: 4, col: 0, part: "frame" },
  { index: 15, row: 4, col: 7, part: "frame" },
  { index: 16, row: 5, col: 0, part: "frame" },
  { index: 17, row: 5, col: 5, part: "corner" },
  { index: 18, row: 5, col: 6, part: "corner" },
  { index: 19, row: 5, col: 7, part: "corner" },
  { index: 20, row: 6, col: 0, part: "frame" },
  { index: 21, row: 6, col: 5, part: "corner" },
  { index: 22, row: 6, col: 6, part: "corner" },
  { index: 23, row: 6, col: 7, part: "corner" },
  { index: 24, row: 7, col: 0, part: "frame" },
  { index: 25, row: 7, col: 1, part: "frame" },
  { index: 26, row: 7, col: 2, part: "frame" },
  { index: 27, row: 7, col: 3, part: "frame" },
  { index: 28, row: 7, col: 4, part: "frame" },
  { index: 29, row: 7, col: 5, part: "corner" },
  { index: 30, row: 7, col: 6, part: "corner" },
  { index: 31, row: 7, col: 7, part: "corner" },
];

/** Archivo 600 set as outlines: identical wherever the font is or is not. */
export const glyphs: readonly LogoGlyph[] = [
  { char: "K", bbox: {"x":73.028,"y":6.642,"width":31.69399999999999,"height":36.358}, d: "M73.028 43V6.642H79.918V23.496L96.03 6.642H104.457L90.359 21.376L104.722 43H96.56L85.695 26.199L79.918 31.287V43Z" },
  { char: "a", bbox: {"x":104.717,"y":14.486,"width":27.400999999999996,"height":29.150000000000002}, d: "M113.515 43.636Q112.349 43.636 110.838 43.344Q109.328 43.053 107.923 42.258Q106.519 41.463 105.618 39.9Q104.717 38.336 104.717 35.792Q104.717 32.93 105.989 31.049Q107.261 29.167 109.566 28.081Q111.872 26.994 115.078 26.544Q118.285 26.093 122.101 26.093V23.814Q122.101 22.595 121.73 21.641Q121.359 20.687 120.379 20.131Q119.398 19.574 117.437 19.574Q115.476 19.574 114.363 20.051Q113.25 20.528 112.826 21.217Q112.402 21.906 112.402 22.648V23.39H106.148Q106.095 23.125 106.095 22.86Q106.095 22.595 106.095 22.224Q106.095 19.839 107.526 18.09Q108.957 16.341 111.501 15.414Q114.045 14.486 117.384 14.486Q121.2 14.486 123.664 15.546Q126.129 16.606 127.348 18.567Q128.567 20.528 128.567 23.337V36.481Q128.567 37.488 129.15 37.912Q129.733 38.336 130.422 38.336H132.118V42.788Q131.588 43 130.581 43.291Q129.574 43.583 128.09 43.583Q126.712 43.583 125.625 43.133Q124.539 42.682 123.797 41.834Q123.055 40.986 122.737 39.82H122.419Q121.518 40.933 120.272 41.808Q119.027 42.682 117.357 43.159Q115.688 43.636 113.515 43.636Z M115.476 38.336Q117.066 38.336 118.311 37.859Q119.557 37.382 120.378 36.534Q121.2 35.686 121.65 34.467Q122.101 33.248 122.101 31.817V30.545Q119.186 30.545 116.721 30.916Q114.257 31.287 112.799 32.294Q111.342 33.301 111.342 35.156Q111.342 36.11 111.792 36.825Q112.243 37.541 113.17 37.938Q114.098 38.336 115.476 38.336Z" },
  { char: "s", bbox: {"x":133.703,"y":14.539,"width":24.538999999999987,"height":29.097}, d: "M145.893 43.636Q142.872 43.636 140.593 42.974Q138.314 42.311 136.777 41.145Q135.24 39.979 134.471 38.416Q133.703 36.852 133.703 34.997Q133.703 34.732 133.73 34.52Q133.756 34.308 133.756 34.202H140.116Q140.116 34.308 140.116 34.414Q140.116 34.52 140.116 34.626Q140.169 36.057 141.017 36.931Q141.865 37.806 143.243 38.177Q144.621 38.548 146.158 38.548Q147.536 38.548 148.781 38.257Q150.027 37.965 150.849 37.303Q151.67 36.64 151.67 35.58Q151.67 34.202 150.61 33.46Q149.55 32.718 147.827 32.241Q146.105 31.764 144.144 31.234Q142.395 30.757 140.646 30.174Q138.897 29.591 137.493 28.69Q136.088 27.789 135.214 26.358Q134.339 24.927 134.339 22.807Q134.339 20.74 135.24 19.203Q136.141 17.666 137.731 16.633Q139.321 15.599 141.494 15.069Q143.667 14.539 146.211 14.539Q148.702 14.539 150.743 15.069Q152.783 15.599 154.293 16.58Q155.804 17.56 156.625 18.965Q157.447 20.369 157.447 22.065Q157.447 22.436 157.421 22.807Q157.394 23.178 157.394 23.231H151.087V22.86Q151.087 21.853 150.477 21.138Q149.868 20.422 148.728 19.998Q147.589 19.574 145.893 19.574Q144.621 19.574 143.667 19.786Q142.713 19.998 142.103 20.369Q141.494 20.74 141.176 21.217Q140.858 21.694 140.858 22.277Q140.858 23.284 141.653 23.867Q142.448 24.45 143.8 24.874Q145.151 25.298 146.741 25.775Q148.649 26.305 150.663 26.861Q152.677 27.418 154.399 28.266Q156.122 29.114 157.182 30.651Q158.242 32.188 158.242 34.732Q158.242 37.17 157.315 38.892Q156.387 40.615 154.718 41.648Q153.048 42.682 150.796 43.159Q148.543 43.636 145.893 43.636Z" },
  { char: "s", bbox: {"x":161.576,"y":14.539,"width":24.539000000000016,"height":29.097}, d: "M173.766 43.636Q170.745 43.636 168.466 42.974Q166.187 42.311 164.65 41.145Q163.113 39.979 162.345 38.416Q161.576 36.852 161.576 34.997Q161.576 34.732 161.603 34.52Q161.629 34.308 161.629 34.202H167.989Q167.989 34.308 167.989 34.414Q167.989 34.52 167.989 34.626Q168.042 36.057 168.89 36.931Q169.738 37.806 171.116 38.177Q172.494 38.548 174.031 38.548Q175.409 38.548 176.655 38.257Q177.9 37.965 178.721 37.303Q179.543 36.64 179.543 35.58Q179.543 34.202 178.483 33.46Q177.423 32.718 175.701 32.241Q173.978 31.764 172.017 31.234Q170.268 30.757 168.519 30.174Q166.77 29.591 165.365 28.69Q163.961 27.789 163.087 26.358Q162.212 24.927 162.212 22.807Q162.212 20.74 163.113 19.203Q164.014 17.666 165.604 16.633Q167.194 15.599 169.367 15.069Q171.54 14.539 174.084 14.539Q176.575 14.539 178.615 15.069Q180.656 15.599 182.167 16.58Q183.677 17.56 184.499 18.965Q185.32 20.369 185.32 22.065Q185.32 22.436 185.294 22.807Q185.267 23.178 185.267 23.231H178.96V22.86Q178.96 21.853 178.351 21.138Q177.741 20.422 176.602 19.998Q175.462 19.574 173.766 19.574Q172.494 19.574 171.54 19.786Q170.586 19.998 169.977 20.369Q169.367 20.74 169.049 21.217Q168.731 21.694 168.731 22.277Q168.731 23.284 169.526 23.867Q170.321 24.45 171.673 24.874Q173.024 25.298 174.614 25.775Q176.522 26.305 178.536 26.861Q180.55 27.418 182.273 28.266Q183.995 29.114 185.055 30.651Q186.115 32.188 186.115 34.732Q186.115 37.17 185.188 38.892Q184.26 40.615 182.591 41.648Q180.921 42.682 178.669 43.159Q176.416 43.636 173.766 43.636Z" },
  { char: "e", bbox: {"x":189.396,"y":14.486,"width":25.599000000000018,"height":29.150000000000002}, d: "M202.752 43.636Q198.3 43.636 195.332 42.073Q192.364 40.509 190.88 37.276Q189.396 34.043 189.396 29.061Q189.396 24.026 190.88 20.819Q192.364 17.613 195.332 16.05Q198.3 14.486 202.752 14.486Q206.78 14.486 209.51 15.997Q212.239 17.507 213.617 20.634Q214.995 23.761 214.995 28.743V30.651H196.021Q196.127 33.248 196.816 35.023Q197.505 36.799 198.963 37.674Q200.42 38.548 202.805 38.548Q204.024 38.548 205.084 38.23Q206.144 37.912 206.939 37.249Q207.734 36.587 208.185 35.58Q208.635 34.573 208.635 33.248H214.995Q214.995 35.898 214.067 37.859Q213.14 39.82 211.471 41.092Q209.801 42.364 207.575 43Q205.349 43.636 202.752 43.636Z M196.127 26.093H208.264Q208.264 24.344 207.867 23.125Q207.469 21.906 206.754 21.111Q206.038 20.316 205.031 19.971Q204.024 19.627 202.752 19.627Q200.685 19.627 199.281 20.316Q197.876 21.005 197.134 22.436Q196.392 23.867 196.127 26.093Z" },
  { char: "n", bbox: {"x":219.707,"y":14.486,"width":24.274,"height":28.514}, d: "M219.707 43V15.122H225.113L225.643 18.832H226.014Q226.968 17.56 228.266 16.58Q229.565 15.599 231.234 15.043Q232.904 14.486 234.918 14.486Q237.568 14.486 239.608 15.44Q241.649 16.394 242.815 18.514Q243.981 20.634 243.981 24.185V43H237.462V25.351Q237.462 23.867 237.117 22.887Q236.773 21.906 236.11 21.297Q235.448 20.687 234.494 20.422Q233.54 20.157 232.374 20.157Q230.625 20.157 229.22 21.005Q227.816 21.853 226.994 23.337Q226.173 24.821 226.173 26.782V43Z" },
  { char: "e", bbox: {"x":248.481,"y":14.486,"width":25.59899999999999,"height":29.150000000000002}, d: "M261.837 43.636Q257.385 43.636 254.417 42.073Q251.449 40.509 249.965 37.276Q248.481 34.043 248.481 29.061Q248.481 24.026 249.965 20.819Q251.449 17.613 254.417 16.05Q257.385 14.486 261.837 14.486Q265.865 14.486 268.594 15.997Q271.324 17.507 272.702 20.634Q274.08 23.761 274.08 28.743V30.651H255.106Q255.212 33.248 255.901 35.023Q256.59 36.799 258.047 37.674Q259.505 38.548 261.89 38.548Q263.109 38.548 264.169 38.23Q265.229 37.912 266.024 37.249Q266.819 36.587 267.269 35.58Q267.72 34.573 267.72 33.248H274.08Q274.08 35.898 273.152 37.859Q272.225 39.82 270.555 41.092Q268.886 42.364 266.66 43Q264.434 43.636 261.837 43.636Z M255.212 26.093H267.349Q267.349 24.344 266.951 23.125Q266.554 21.906 265.838 21.111Q265.123 20.316 264.116 19.971Q263.109 19.627 261.837 19.627Q259.77 19.627 258.365 20.316Q256.961 21.005 256.219 22.436Q255.477 23.867 255.212 26.093Z" },
  { char: "c", bbox: {"x":277.414,"y":14.486,"width":24.857000000000028,"height":29.150000000000002}, d: "M290.399 43.636Q286.053 43.636 283.164 42.073Q280.276 40.509 278.845 37.276Q277.414 34.043 277.414 29.061Q277.414 24.026 278.871 20.819Q280.329 17.613 283.217 16.05Q286.106 14.486 290.399 14.486Q293.208 14.486 295.381 15.175Q297.554 15.864 299.117 17.269Q300.681 18.673 301.476 20.74Q302.271 22.807 302.271 25.563H295.699Q295.699 23.602 295.116 22.33Q294.533 21.058 293.34 20.395Q292.148 19.733 290.293 19.733Q288.12 19.733 286.742 20.74Q285.364 21.747 284.702 23.735Q284.039 25.722 284.039 28.743V29.432Q284.039 32.4 284.702 34.414Q285.364 36.428 286.795 37.409Q288.226 38.389 290.558 38.389Q292.36 38.389 293.553 37.727Q294.745 37.064 295.381 35.739Q296.017 34.414 296.017 32.559H302.271Q302.271 35.156 301.476 37.223Q300.681 39.29 299.144 40.721Q297.607 42.152 295.407 42.894Q293.208 43.636 290.399 43.636Z" },
  { char: "k", bbox: {"x":306.983,"y":4.681,"width":24.591999999999985,"height":38.319}, d: "M306.983 43V4.681H313.449V26.994L323.466 15.122H331.045L321.717 25.934L331.575 43H324.155L317.583 30.651L313.449 34.626V43Z" },
];

export const animations: Readonly<Record<string, Animation>> = {
  "rain": {
    "name": "rain",
    "de": "Regen",
    "scenario": "splash",
    "duration": 1600,
    "loop": false,
    "tracks": [
      {
        "kind": "cell",
        "indices": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24,
          25,
          26,
          27,
          28,
          29,
          30,
          31
        ],
        "shuffle": true,
        "start": 0,
        "stagger": 22,
        "duration": 520,
        "easing": "out-cubic",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "dy": -9
          },
          {
            "at": 1,
            "opacity": 1,
            "dy": 0
          }
        ]
      },
      {
        "kind": "glyph",
        "indices": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8
        ],
        "shuffle": false,
        "start": 900,
        "stagger": 30,
        "duration": 300,
        "easing": "out-cubic",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0
          },
          {
            "at": 1,
            "opacity": 1
          }
        ]
      }
    ]
  },
  "bloom": {
    "name": "bloom",
    "de": "Aufblühen",
    "scenario": "splash",
    "duration": 1400,
    "loop": false,
    "tracks": [
      {
        "kind": "cell",
        "indices": [
          22,
          18,
          21,
          23,
          30,
          17,
          19,
          29,
          31,
          15,
          28,
          13,
          27,
          11,
          26,
          9,
          25,
          6,
          20,
          5,
          7,
          16,
          24,
          4,
          14,
          3,
          12,
          2,
          10,
          1,
          8,
          0
        ],
        "shuffle": false,
        "start": 0,
        "stagger": 26,
        "duration": 360,
        "easing": "out-back",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "scale": 0
          },
          {
            "at": 1,
            "opacity": 1,
            "scale": 1
          }
        ]
      },
      {
        "kind": "glyph",
        "indices": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8
        ],
        "shuffle": false,
        "start": 600,
        "stagger": 40,
        "duration": 400,
        "easing": "out-cubic",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "scale": 0.6
          },
          {
            "at": 1,
            "opacity": 1,
            "scale": 1
          }
        ]
      }
    ]
  },
  "scatter": {
    "name": "scatter",
    "de": "Zufall",
    "scenario": "splash",
    "duration": 1400,
    "loop": false,
    "tracks": [
      {
        "kind": "cell",
        "indices": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24,
          25,
          26,
          27,
          28,
          29,
          30,
          31
        ],
        "shuffle": true,
        "start": 0,
        "stagger": 22,
        "duration": 320,
        "easing": "out-back",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "scale": 0
          },
          {
            "at": 1,
            "opacity": 1,
            "scale": 1
          }
        ]
      },
      {
        "kind": "glyph",
        "indices": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8
        ],
        "shuffle": true,
        "start": 500,
        "stagger": 70,
        "duration": 260,
        "easing": "out-cubic",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "scale": 0.7
          },
          {
            "at": 1,
            "opacity": 1,
            "scale": 1
          }
        ]
      }
    ]
  },
  "heart": {
    "name": "heart",
    "de": "Herz",
    "scenario": "splash",
    "duration": 2100,
    "loop": false,
    "tracks": [
      {
        "kind": "pixel",
        "indices": [
          9,
          10,
          13,
          14,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24,
          25,
          26,
          27,
          28,
          29,
          30,
          31,
          33,
          34,
          35,
          36,
          37,
          38,
          42,
          43,
          44,
          45,
          51,
          52
        ],
        "shuffle": true,
        "start": 0,
        "stagger": 22,
        "duration": 120,
        "easing": "out-cubic",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "accent": 1
          },
          {
            "at": 1,
            "opacity": 1,
            "accent": 1
          }
        ]
      },
      {
        "kind": "pixel",
        "indices": [
          9,
          10,
          13,
          14,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24,
          25,
          26,
          27,
          28,
          29,
          30,
          31,
          33,
          34,
          35,
          36,
          37,
          38,
          42,
          43,
          44,
          45,
          51,
          52
        ],
        "shuffle": false,
        "start": 1000,
        "stagger": 0,
        "duration": 0,
        "easing": "step",
        "wrap": false,
        "before": "none",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 1,
            "accent": 1
          },
          {
            "at": 1,
            "opacity": 0,
            "accent": 1
          }
        ]
      },
      {
        "kind": "pixel",
        "indices": [
          20,
          22,
          27,
          28,
          29,
          30,
          31,
          35,
          36,
          37,
          38,
          39,
          44,
          45,
          46,
          53
        ],
        "shuffle": false,
        "start": 1000,
        "stagger": 0,
        "duration": 180,
        "easing": "linear",
        "wrap": false,
        "before": "none",
        "after": "none",
        "keyframes": [
          {
            "at": 0,
            "opacity": 1,
            "accent": 1
          }
        ]
      },
      {
        "kind": "pixel",
        "indices": [
          37,
          39,
          45,
          46,
          47,
          54
        ],
        "shuffle": false,
        "start": 1180,
        "stagger": 0,
        "duration": 180,
        "easing": "linear",
        "wrap": false,
        "before": "none",
        "after": "none",
        "keyframes": [
          {
            "at": 0,
            "opacity": 1,
            "accent": 1
          }
        ]
      },
      {
        "kind": "cell",
        "indices": [
          17,
          18,
          19,
          21,
          22,
          23,
          29,
          30,
          31
        ],
        "shuffle": false,
        "start": 1360,
        "stagger": 0,
        "duration": 0,
        "easing": "step",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0
          },
          {
            "at": 1,
            "opacity": 1
          }
        ]
      },
      {
        "kind": "cell",
        "indices": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          20,
          24,
          25,
          26,
          27,
          28
        ],
        "shuffle": true,
        "start": 1000,
        "stagger": 16,
        "duration": 220,
        "easing": "out-back",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "scale": 0.3
          },
          {
            "at": 1,
            "opacity": 1,
            "scale": 1
          }
        ]
      },
      {
        "kind": "glyph",
        "indices": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8
        ],
        "shuffle": false,
        "start": 1450,
        "stagger": 40,
        "duration": 300,
        "easing": "out-cubic",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "dy": 0.5
          },
          {
            "at": 1,
            "opacity": 1,
            "dy": 0
          }
        ]
      }
    ]
  },
  "euro": {
    "name": "euro",
    "de": "Euro",
    "scenario": "splash",
    "duration": 2100,
    "loop": false,
    "tracks": [
      {
        "kind": "pixel",
        "indices": [
          3,
          4,
          5,
          6,
          10,
          15,
          17,
          24,
          25,
          26,
          27,
          33,
          40,
          41,
          42,
          43,
          50,
          55,
          59,
          60,
          61,
          62
        ],
        "shuffle": true,
        "start": 0,
        "stagger": 16,
        "duration": 220,
        "easing": "out-back",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "scale": 0.3
          },
          {
            "at": 1,
            "opacity": 1,
            "scale": 1
          }
        ]
      },
      {
        "kind": "pixel",
        "indices": [
          3,
          4,
          5,
          6,
          10,
          15,
          17,
          24,
          25,
          26,
          33,
          40,
          41,
          42,
          50,
          59,
          60
        ],
        "shuffle": false,
        "start": 800,
        "stagger": 0,
        "duration": 500,
        "easing": "in-out-cubic",
        "wrap": false,
        "before": "none",
        "after": "none",
        "keyframes": [
          {
            "at": 0,
            "move": 0
          },
          {
            "at": 1,
            "move": 1
          }
        ],
        "vectors": [
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            -1
          ],
          [
            0,
            0
          ],
          [
            -1,
            0
          ],
          [
            0,
            0
          ],
          [
            -1,
            -2
          ],
          [
            -1,
            -3
          ],
          [
            -1,
            0
          ],
          [
            0,
            0
          ],
          [
            -1,
            1
          ],
          [
            -1,
            2
          ],
          [
            0,
            1
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ]
        ]
      },
      {
        "kind": "pixel",
        "indices": [
          27,
          43,
          55,
          61,
          62
        ],
        "shuffle": false,
        "start": 800,
        "stagger": 0,
        "duration": 500,
        "easing": "in-out-cubic",
        "wrap": false,
        "before": "none",
        "after": "none",
        "keyframes": [
          {
            "at": 0,
            "move": 0,
            "accent": 0
          },
          {
            "at": 1,
            "move": 1,
            "accent": 1
          }
        ],
        "vectors": [
          [
            3,
            2
          ],
          [
            2,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ]
        ]
      },
      {
        "kind": "pixel",
        "indices": [
          3,
          4,
          5,
          6,
          10,
          15,
          17,
          24,
          25,
          26,
          27,
          33,
          40,
          41,
          42,
          43,
          50,
          55,
          59,
          60,
          61,
          62
        ],
        "shuffle": false,
        "start": 1300,
        "stagger": 0,
        "duration": 0,
        "easing": "step",
        "wrap": false,
        "before": "none",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 1
          },
          {
            "at": 1,
            "opacity": 0
          }
        ]
      },
      {
        "kind": "cell",
        "indices": [
          1,
          2,
          3,
          4,
          5,
          6,
          8,
          9,
          10,
          12,
          14,
          16,
          17,
          18,
          20,
          23,
          25,
          26,
          27,
          28,
          29,
          30
        ],
        "shuffle": false,
        "start": 1300,
        "stagger": 0,
        "duration": 0,
        "easing": "step",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0
          },
          {
            "at": 1,
            "opacity": 1
          }
        ]
      },
      {
        "kind": "cell",
        "indices": [
          0,
          7,
          11,
          13,
          15,
          19,
          21,
          22,
          24,
          31
        ],
        "shuffle": true,
        "start": 1300,
        "stagger": 10,
        "duration": 200,
        "easing": "out-back",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "scale": 0.3
          },
          {
            "at": 1,
            "opacity": 1,
            "scale": 1
          }
        ]
      },
      {
        "kind": "glyph",
        "indices": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8
        ],
        "shuffle": false,
        "start": 1400,
        "stagger": 40,
        "duration": 300,
        "easing": "out-cubic",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "dy": 0.5
          },
          {
            "at": 1,
            "opacity": 1,
            "dy": 0
          }
        ]
      }
    ]
  },
  "check": {
    "name": "check",
    "de": "Haken",
    "scenario": "splash",
    "duration": 2100,
    "loop": false,
    "tracks": [
      {
        "kind": "pixel",
        "indices": [
          15,
          22,
          23,
          29,
          30,
          32,
          36,
          37,
          40,
          41,
          43,
          44,
          49,
          50,
          51,
          58
        ],
        "shuffle": true,
        "start": 0,
        "stagger": 16,
        "duration": 220,
        "easing": "out-back",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "scale": 0.3
          },
          {
            "at": 1,
            "opacity": 1,
            "scale": 1
          }
        ]
      },
      {
        "kind": "pixel",
        "indices": [
          15,
          22,
          23,
          29,
          30,
          32,
          40,
          41,
          43,
          49,
          50,
          51,
          58
        ],
        "shuffle": false,
        "start": 800,
        "stagger": 0,
        "duration": 500,
        "easing": "in-out-cubic",
        "wrap": false,
        "before": "none",
        "after": "none",
        "keyframes": [
          {
            "at": 0,
            "move": 0
          },
          {
            "at": 1,
            "move": 1
          }
        ],
        "vectors": [
          [
            0,
            0
          ],
          [
            0,
            -2
          ],
          [
            0,
            0
          ],
          [
            2,
            1
          ],
          [
            1,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            -1,
            -2
          ],
          [
            1,
            2
          ],
          [
            -1,
            0
          ],
          [
            -1,
            1
          ],
          [
            0,
            1
          ],
          [
            0,
            0
          ]
        ]
      },
      {
        "kind": "pixel",
        "indices": [
          36,
          37,
          44
        ],
        "shuffle": false,
        "start": 800,
        "stagger": 0,
        "duration": 500,
        "easing": "in-out-cubic",
        "wrap": false,
        "before": "none",
        "after": "none",
        "keyframes": [
          {
            "at": 0,
            "move": 0,
            "accent": 0
          },
          {
            "at": 1,
            "move": 1,
            "accent": 1
          }
        ],
        "vectors": [
          [
            2,
            1
          ],
          [
            0,
            1
          ],
          [
            1,
            1
          ]
        ]
      },
      {
        "kind": "pixel",
        "indices": [
          15,
          22,
          23,
          29,
          30,
          32,
          36,
          37,
          40,
          41,
          43,
          44,
          49,
          50,
          51,
          58
        ],
        "shuffle": false,
        "start": 1300,
        "stagger": 0,
        "duration": 0,
        "easing": "step",
        "wrap": false,
        "before": "none",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 1
          },
          {
            "at": 1,
            "opacity": 0
          }
        ]
      },
      {
        "kind": "cell",
        "indices": [
          6,
          9,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          20,
          21,
          25,
          26,
          27,
          28
        ],
        "shuffle": false,
        "start": 1300,
        "stagger": 0,
        "duration": 0,
        "easing": "step",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0
          },
          {
            "at": 1,
            "opacity": 1
          }
        ]
      },
      {
        "kind": "cell",
        "indices": [
          0,
          1,
          2,
          3,
          4,
          5,
          7,
          8,
          10,
          19,
          22,
          23,
          24,
          29,
          30,
          31
        ],
        "shuffle": true,
        "start": 1300,
        "stagger": 10,
        "duration": 200,
        "easing": "out-back",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "scale": 0.3
          },
          {
            "at": 1,
            "opacity": 1,
            "scale": 1
          }
        ]
      },
      {
        "kind": "glyph",
        "indices": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8
        ],
        "shuffle": false,
        "start": 1400,
        "stagger": 40,
        "duration": 300,
        "easing": "out-cubic",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "dy": 0.5
          },
          {
            "at": 1,
            "opacity": 1,
            "dy": 0
          }
        ]
      }
    ]
  },
  "star": {
    "name": "star",
    "de": "Stern",
    "scenario": "splash",
    "duration": 2100,
    "loop": false,
    "tracks": [
      {
        "kind": "pixel",
        "indices": [
          3,
          10,
          11,
          12,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          25,
          26,
          27,
          28,
          29,
          34,
          35,
          36,
          41,
          42,
          44,
          45,
          48,
          54
        ],
        "shuffle": true,
        "start": 0,
        "stagger": 16,
        "duration": 220,
        "easing": "out-back",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "scale": 0.3
          },
          {
            "at": 1,
            "opacity": 1,
            "scale": 1
          }
        ]
      },
      {
        "kind": "pixel",
        "indices": [
          3,
          10,
          11,
          12,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          25,
          26,
          27,
          28,
          29,
          34,
          35,
          41,
          42,
          48
        ],
        "shuffle": false,
        "start": 800,
        "stagger": 0,
        "duration": 500,
        "easing": "in-out-cubic",
        "wrap": false,
        "before": "none",
        "after": "none",
        "keyframes": [
          {
            "at": 0,
            "move": 0
          },
          {
            "at": 1,
            "move": 1
          }
        ],
        "vectors": [
          [
            0,
            0
          ],
          [
            0,
            -1
          ],
          [
            -2,
            -1
          ],
          [
            0,
            -1
          ],
          [
            0,
            0
          ],
          [
            -1,
            -1
          ],
          [
            -2,
            -2
          ],
          [
            4,
            -1
          ],
          [
            2,
            -2
          ],
          [
            0,
            -2
          ],
          [
            1,
            0
          ],
          [
            -1,
            0
          ],
          [
            -1,
            4
          ],
          [
            1,
            4
          ],
          [
            3,
            1
          ],
          [
            2,
            0
          ],
          [
            -2,
            0
          ],
          [
            0,
            3
          ],
          [
            -1,
            0
          ],
          [
            0,
            2
          ],
          [
            0,
            0
          ]
        ]
      },
      {
        "kind": "pixel",
        "indices": [
          36,
          44,
          45,
          54
        ],
        "shuffle": false,
        "start": 800,
        "stagger": 0,
        "duration": 500,
        "easing": "in-out-cubic",
        "wrap": false,
        "before": "none",
        "after": "none",
        "keyframes": [
          {
            "at": 0,
            "move": 0,
            "accent": 0
          },
          {
            "at": 1,
            "move": 1,
            "accent": 1
          }
        ],
        "vectors": [
          [
            2,
            1
          ],
          [
            1,
            1
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ]
        ]
      },
      {
        "kind": "pixel",
        "indices": [
          3,
          10,
          11,
          12,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          25,
          26,
          27,
          28,
          29,
          34,
          35,
          36,
          41,
          42,
          44,
          45,
          48,
          54
        ],
        "shuffle": false,
        "start": 1300,
        "stagger": 0,
        "duration": 0,
        "easing": "step",
        "wrap": false,
        "before": "none",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 1
          },
          {
            "at": 1,
            "opacity": 0
          }
        ]
      },
      {
        "kind": "cell",
        "indices": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          20,
          21,
          22,
          25,
          26,
          27,
          28
        ],
        "shuffle": false,
        "start": 1300,
        "stagger": 0,
        "duration": 0,
        "easing": "step",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0
          },
          {
            "at": 1,
            "opacity": 1
          }
        ]
      },
      {
        "kind": "cell",
        "indices": [
          7,
          19,
          23,
          24,
          29,
          30,
          31
        ],
        "shuffle": true,
        "start": 1300,
        "stagger": 10,
        "duration": 200,
        "easing": "out-back",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "scale": 0.3
          },
          {
            "at": 1,
            "opacity": 1,
            "scale": 1
          }
        ]
      },
      {
        "kind": "glyph",
        "indices": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8
        ],
        "shuffle": false,
        "start": 1400,
        "stagger": 40,
        "duration": 300,
        "easing": "out-cubic",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "dy": 0.5
          },
          {
            "at": 1,
            "opacity": 1,
            "dy": 0
          }
        ]
      }
    ]
  },
  "lock": {
    "name": "lock",
    "de": "Schloss",
    "scenario": "splash",
    "duration": 2100,
    "loop": false,
    "tracks": [
      {
        "kind": "pixel",
        "indices": [
          2,
          3,
          4,
          5,
          9,
          14,
          17,
          22,
          24,
          25,
          26,
          27,
          28,
          29,
          30,
          31,
          32,
          33,
          34,
          35,
          36,
          37,
          38,
          39,
          40,
          41,
          42,
          45,
          46,
          47,
          48,
          49,
          50,
          53,
          54,
          55,
          56,
          57,
          58,
          59,
          60,
          61,
          62,
          63
        ],
        "shuffle": true,
        "start": 0,
        "stagger": 16,
        "duration": 220,
        "easing": "out-back",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "scale": 0.3
          },
          {
            "at": 1,
            "opacity": 1,
            "scale": 1
          }
        ]
      },
      {
        "kind": "pixel",
        "indices": [
          2,
          3,
          4,
          5,
          9,
          14,
          17,
          22,
          24,
          25,
          26,
          29,
          30,
          31,
          32,
          33,
          34,
          38,
          39,
          40,
          41,
          42,
          48,
          49,
          50,
          56,
          57,
          58,
          59,
          60
        ],
        "shuffle": false,
        "start": 800,
        "stagger": 0,
        "duration": 500,
        "easing": "in-out-cubic",
        "wrap": false,
        "before": "none",
        "after": "none",
        "keyframes": [
          {
            "at": 0,
            "move": 0
          },
          {
            "at": 1,
            "move": 1
          }
        ],
        "vectors": [
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            -1
          ],
          [
            0,
            -1
          ],
          [
            -1,
            0
          ],
          [
            1,
            0
          ],
          [
            0,
            0
          ],
          [
            -1,
            -2
          ],
          [
            -2,
            -3
          ],
          [
            2,
            -3
          ],
          [
            1,
            -2
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            -1,
            0
          ],
          [
            -2,
            0
          ],
          [
            1,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            -1,
            0
          ],
          [
            -2,
            0
          ],
          [
            0,
            0
          ],
          [
            -1,
            0
          ],
          [
            0,
            1
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ]
        ]
      },
      {
        "kind": "pixel",
        "indices": [
          27,
          28,
          35,
          36,
          37,
          45,
          46,
          47,
          53,
          54,
          55,
          61,
          62,
          63
        ],
        "shuffle": false,
        "start": 800,
        "stagger": 0,
        "duration": 500,
        "easing": "in-out-cubic",
        "wrap": false,
        "before": "none",
        "after": "none",
        "keyframes": [
          {
            "at": 0,
            "move": 0,
            "accent": 0
          },
          {
            "at": 1,
            "move": 1,
            "accent": 1
          }
        ],
        "vectors": [
          [
            2,
            2
          ],
          [
            1,
            2
          ],
          [
            2,
            1
          ],
          [
            1,
            1
          ],
          [
            0,
            1
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ]
        ]
      },
      {
        "kind": "pixel",
        "indices": [
          2,
          3,
          4,
          5,
          9,
          14,
          17,
          22,
          24,
          25,
          26,
          27,
          28,
          29,
          30,
          31,
          32,
          33,
          34,
          35,
          36,
          37,
          38,
          39,
          40,
          41,
          42,
          45,
          46,
          47,
          48,
          49,
          50,
          53,
          54,
          55,
          56,
          57,
          58,
          59,
          60,
          61,
          62,
          63
        ],
        "shuffle": false,
        "start": 1300,
        "stagger": 0,
        "duration": 0,
        "easing": "step",
        "wrap": false,
        "before": "none",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 1
          },
          {
            "at": 1,
            "opacity": 0
          }
        ]
      },
      {
        "kind": "cell",
        "indices": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24,
          25,
          26,
          27,
          28,
          29,
          30,
          31
        ],
        "shuffle": false,
        "start": 1300,
        "stagger": 0,
        "duration": 0,
        "easing": "step",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0
          },
          {
            "at": 1,
            "opacity": 1
          }
        ]
      },
      {
        "kind": "cell",
        "indices": [],
        "shuffle": true,
        "start": 1300,
        "stagger": 10,
        "duration": 200,
        "easing": "out-back",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "scale": 0.3
          },
          {
            "at": 1,
            "opacity": 1,
            "scale": 1
          }
        ]
      },
      {
        "kind": "glyph",
        "indices": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8
        ],
        "shuffle": false,
        "start": 1400,
        "stagger": 40,
        "duration": 300,
        "easing": "out-cubic",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "dy": 0.5
          },
          {
            "at": 1,
            "opacity": 1,
            "dy": 0
          }
        ]
      }
    ]
  },
  "receipt": {
    "name": "receipt",
    "de": "Bon",
    "scenario": "splash",
    "duration": 2100,
    "loop": false,
    "tracks": [
      {
        "kind": "pixel",
        "indices": [
          1,
          2,
          3,
          4,
          5,
          6,
          9,
          14,
          17,
          19,
          20,
          22,
          25,
          30,
          33,
          35,
          36,
          38,
          41,
          46,
          49,
          51,
          52,
          54,
          57,
          59,
          61,
          62
        ],
        "shuffle": true,
        "start": 0,
        "stagger": 16,
        "duration": 220,
        "easing": "out-back",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "scale": 0.3
          },
          {
            "at": 1,
            "opacity": 1,
            "scale": 1
          }
        ]
      },
      {
        "kind": "pixel",
        "indices": [
          1,
          2,
          3,
          4,
          5,
          6,
          9,
          14,
          17,
          19,
          20,
          22,
          25,
          30,
          33,
          35,
          38,
          41,
          49,
          51,
          57,
          59
        ],
        "shuffle": false,
        "start": 800,
        "stagger": 0,
        "duration": 500,
        "easing": "in-out-cubic",
        "wrap": false,
        "before": "none",
        "after": "none",
        "keyframes": [
          {
            "at": 0,
            "move": 0
          },
          {
            "at": 1,
            "move": 1
          }
        ],
        "vectors": [
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            -1,
            0
          ],
          [
            1,
            0
          ],
          [
            -1,
            0
          ],
          [
            -3,
            -2
          ],
          [
            3,
            -2
          ],
          [
            1,
            0
          ],
          [
            -1,
            0
          ],
          [
            1,
            0
          ],
          [
            -1,
            0
          ],
          [
            1,
            3
          ],
          [
            1,
            0
          ],
          [
            -1,
            0
          ],
          [
            -1,
            0
          ],
          [
            -1,
            1
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ]
        ]
      },
      {
        "kind": "pixel",
        "indices": [
          36,
          46,
          52,
          54,
          61,
          62
        ],
        "shuffle": false,
        "start": 800,
        "stagger": 0,
        "duration": 500,
        "easing": "in-out-cubic",
        "wrap": false,
        "before": "none",
        "after": "none",
        "keyframes": [
          {
            "at": 0,
            "move": 0,
            "accent": 0
          },
          {
            "at": 1,
            "move": 1,
            "accent": 1
          }
        ],
        "vectors": [
          [
            1,
            1
          ],
          [
            0,
            0
          ],
          [
            1,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ],
          [
            0,
            0
          ]
        ]
      },
      {
        "kind": "pixel",
        "indices": [
          1,
          2,
          3,
          4,
          5,
          6,
          9,
          14,
          17,
          19,
          20,
          22,
          25,
          30,
          33,
          35,
          36,
          38,
          41,
          46,
          49,
          51,
          52,
          54,
          57,
          59,
          61,
          62
        ],
        "shuffle": false,
        "start": 1300,
        "stagger": 0,
        "duration": 0,
        "easing": "step",
        "wrap": false,
        "before": "none",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 1
          },
          {
            "at": 1,
            "opacity": 0
          }
        ]
      },
      {
        "kind": "cell",
        "indices": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          20,
          21,
          22,
          25,
          26,
          27,
          28,
          29,
          30
        ],
        "shuffle": false,
        "start": 1300,
        "stagger": 0,
        "duration": 0,
        "easing": "step",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0
          },
          {
            "at": 1,
            "opacity": 1
          }
        ]
      },
      {
        "kind": "cell",
        "indices": [
          19,
          23,
          24,
          31
        ],
        "shuffle": true,
        "start": 1300,
        "stagger": 10,
        "duration": 200,
        "easing": "out-back",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "scale": 0.3
          },
          {
            "at": 1,
            "opacity": 1,
            "scale": 1
          }
        ]
      },
      {
        "kind": "glyph",
        "indices": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8
        ],
        "shuffle": false,
        "start": 1400,
        "stagger": 40,
        "duration": 300,
        "easing": "out-cubic",
        "wrap": false,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "opacity": 0,
            "dy": 0.5
          },
          {
            "at": 1,
            "opacity": 1,
            "dy": 0
          }
        ]
      }
    ]
  },
  "breathe": {
    "name": "breathe",
    "de": "Atmen",
    "scenario": "waiting",
    "duration": 2400,
    "loop": true,
    "tracks": [
      {
        "kind": "cell",
        "indices": [
          22,
          18,
          21,
          23,
          30,
          17,
          19,
          29,
          31,
          15,
          28,
          13,
          27,
          11,
          26,
          9,
          25,
          6,
          20,
          5,
          7,
          16,
          24,
          4,
          14,
          3,
          12,
          2,
          10,
          1,
          8,
          0
        ],
        "shuffle": false,
        "start": 0,
        "stagger": 30,
        "duration": 1200,
        "easing": "in-out-sine",
        "wrap": true,
        "before": "hold",
        "after": "hold",
        "keyframes": [
          {
            "at": 0,
            "scale": 1
          },
          {
            "at": 0.5,
            "scale": 0.6
          },
          {
            "at": 1,
            "scale": 1
          }
        ]
      }
    ]
  },
};

export const animationNames = ["rain","bloom","scatter","heart","euro","check","star","lock","receipt","breathe"] as const;
export type AnimationName = (typeof animationNames)[number];
