// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const ArchiveRestore = /* @__PURE__ */ createIcon("archive-restore", [
    ["rect", { x: "3", y: "4", width: "18", height: "4", rx: "2" }],
    ["path", { d: "M5 8v11a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8" }],
    ["path", { d: "M12 17v-6M9.5 13.5L12 11l2.5 2.5" }]
]);
