// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Archive = /* @__PURE__ */ createIcon("archive", [
    ["rect", { x: "3", y: "4", width: "18", height: "4", rx: "2" }],
    ["path", { d: "M5 8v11a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8" }],
    ["path", { d: "M10 12h4" }]
]);
