// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const ArrowRight = /* @__PURE__ */ createIcon("arrow-right", [
    ["path", { d: "M5 12h14M13 6l6 6-6 6" }]
]);
