// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const ArrowDown = /* @__PURE__ */ createIcon("arrow-down", [
    ["path", { d: "M12 5v14M6 13l6 6 6-6" }]
]);
