// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Backspace = /* @__PURE__ */ createIcon("backspace", [
    ["path", { d: "M21 5H9l-6 7 6 7h12a1.5 1.5 0 0 0 1.5 -1.5v-11A1.5 1.5 0 0 0 21 5z" }],
    ["path", { d: "M12.5 9.5l5 5M17.5 9.5l-5 5" }]
]);
