// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const BadgeCheck = /* @__PURE__ */ createIcon("badge-check", [
    ["path", { d: "M12 3l2.2 1.6 2.7-.3 1 2.5 2.5 1-.3 2.7L21.7 12l-1.6 2.2.3 2.7-2.5 1-1 2.5-2.7-.3L12 21.7l-2.2-1.6-2.7.3-1-2.5-2.5-1 .3-2.7L2.3 12l1.6-2.2-.3-2.7 2.5-1 1-2.5 2.7.3z" }],
    ["path", { d: "M8 12.5l2.5 2.5L16 9.5" }]
]);
