// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Ban = /* @__PURE__ */ createIcon("ban", [
    ["circle", { cx: "12", cy: "12", r: "9" }],
    ["path", { d: "M5.6 5.6l12.8 12.8" }]
]);
