// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Banknote = createIcon("banknote", [
    ["rect", { x: "2.5", y: "6", width: "19", height: "12", rx: "2.5" }],
    ["circle", { cx: "12", cy: "12", r: "2.5" }],
    ["path", { d: "M6.5 12h.1M17.5 12h.1" }]
]);
