// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Barcode = /* @__PURE__ */ createIcon("barcode", [
    ["path", { d: "M3.5 5v14M6.5 5v14M9.5 5v14M12.5 5v14M15.5 5v14M18.5 5v14M21.5 5v14" }]
]);
