// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const BluetoothConnected = createIcon("bluetooth-connected", [
    ["path", { d: "M7 7l10 10-5 5V3l5 5L7 17" }],
    ["path", { d: "M4 12h.1M20 12h.1" }]
]);
