// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Bluetooth = /* @__PURE__ */ createIcon("bluetooth", [
    ["path", { d: "M7 7l10 10-5 5V3l5 5L7 17" }]
]);
