// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Book = createIcon("book", [
    ["path", { d: "M4 4h6a3 3 0 0 1 3 3v14a2 2 0 0 0-2-2H4z" }],
    ["path", { d: "M20 4h-6a3 3 0 0 0-3 3v14a2 2 0 0 1 2-2h7z" }]
]);
