// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Boxes = /* @__PURE__ */ createIcon("boxes", [
    ["rect", { x: "3", y: "14", width: "7", height: "7", rx: "1" }],
    ["rect", { x: "14", y: "14", width: "7", height: "7", rx: "1" }],
    ["rect", { x: "8.5", y: "3", width: "7", height: "7", rx: "1" }]
]);
