// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Briefcase = createIcon("briefcase", [
    ["rect", { x: "3", y: "7", width: "18", height: "13", rx: "2.5" }],
    ["path", { d: "M9 7V4h6v3" }],
    ["path", { d: "M3 13h18" }]
]);
