// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Brush = /* @__PURE__ */ createIcon("brush", [
    ["path", { d: "M18.4 3.6L9 13l2 2 9.4-9.4a1.4 1.4 0 0 0-2-2z" }],
    ["path", { d: "M9 13c-3 0-4 2-4 4s-2 2-2 2c3 1 7 0 8-2s0-4 0-4" }]
]);
