// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Building = /* @__PURE__ */ createIcon("building", [
    ["rect", { x: "4", y: "3", width: "16", height: "18", rx: "2.5" }],
    ["path", { d: "M9 8h.1M15 8h.1M9 13h.1M15 13h.1" }],
    ["path", { d: "M10 21v-4h4v4" }]
]);
