// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Cable = /* @__PURE__ */ createIcon("cable", [
    ["rect", { x: "8", y: "3", width: "8", height: "7", rx: "1" }],
    ["path", { d: "M10 10v4a2 2 0 0 0 4 0v-4" }],
    ["path", { d: "M12 16v5" }]
]);
