// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Calendar = createIcon("calendar", [
    ["rect", { x: "3", y: "5", width: "18", height: "16", rx: "2.5" }],
    ["path", { d: "M3 10h18M8 3v4M16 3v4" }]
]);
