// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const CalendarClock = createIcon("calendar-clock", [
    ["path", { d: "M3 5H15V8L7 17H3Z" }],
    ["path", { d: "M3 8h12M6 3v4M11 3v4" }],
    ["circle", { cx: "17", cy: "17", r: "4" }],
    ["path", { d: "M17 15v2l1.5 1" }]
]);
