// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const CalendarClock = /* @__PURE__ */ createIcon("calendar-clock", [
    ["path", { d: "M21 10V7.5a2.5 2.5 0 0 0-2.5-2.5h-13A2.5 2.5 0 0 0 3 7.5v11A2.5 2.5 0 0 0 5.5 21H10" }],
    ["path", { d: "M3 10h18M8 3v4M16 3v4" }],
    ["circle", { cx: "17", cy: "17.5", r: "4" }],
    ["path", { d: "M17 15.5V17.5L18.5 19" }]
]);
