// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const CashDrawer = createIcon("cash-drawer", [
    ["path", { d: "M5 10V6h14v4" }],
    ["rect", { x: "3", y: "10", width: "18", height: "10", rx: "2.5" }],
    ["path", { d: "M10 15h4" }]
]);
