// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const ChartBar = createIcon("chart-bar", [
    ["path", { d: "M3 3v18h18" }],
    ["path", { d: "M8 17V11M13 17V7M18 17v-3" }]
]);
