// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const CheckCircle = /* @__PURE__ */ createIcon("check-circle", [
    ["circle", { cx: "12", cy: "12", r: "9" }],
    ["path", { d: "M8 12.5l2.5 2.5L16 9.5" }]
]);
