// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Check = /* @__PURE__ */ createIcon("check", [
    ["path", { d: "M5 12.5l4.5 4.5L19 7" }]
]);
