// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const ChevronDown = /* @__PURE__ */ createIcon("chevron-down", [
    ["path", { d: "M6 9l6 6 6-6" }]
]);
