// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const ChevronUp = /* @__PURE__ */ createIcon("chevron-up", [
    ["path", { d: "M6 15l6-6 6 6" }]
]);
