// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const ChevronRight = /* @__PURE__ */ createIcon("chevron-right", [
    ["path", { d: "M9 6l6 6-6 6" }]
]);
