// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Circle = /* @__PURE__ */ createIcon("circle", [
    ["circle", { cx: "12", cy: "12", r: "9" }]
]);
