// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const CircleDashed = /* @__PURE__ */ createIcon("circle-dashed", [
    ["path", { d: "M21 12A9 9 0 0 1 19.8 16.5M18.4 18.4A9 9 0 0 1 14.3 20.7M12 21A9 9 0 0 1 7.5 19.8M5.6 18.4A9 9 0 0 1 3.3 14.3M3 12A9 9 0 0 1 4.2 7.5M5.6 5.6A9 9 0 0 1 9.7 3.3M12 3A9 9 0 0 1 16.5 4.2M18.4 5.6A9 9 0 0 1 20.7 9.7" }]
]);
