// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const CircleFilled = createIcon("circle-filled", [
    ["circle", { cx: "12", cy: "12", r: "9", fill: "currentColor" }]
], { filled: true });
