// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Clipboard = /* @__PURE__ */ createIcon("clipboard", [
    ["rect", { x: "5", y: "4", width: "14", height: "17", rx: "2.5" }],
    ["path", { d: "M9 4V3h6v1" }],
    ["path", { d: "M9 11h6M9 15h4" }]
]);
