// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Clock = createIcon("clock", [
    ["circle", { cx: "12", cy: "12", r: "9" }],
    ["path", { d: "M12 7v5l3 2" }]
]);
