// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Coins = /* @__PURE__ */ createIcon("coins", [
    ["circle", { cx: "9", cy: "9", r: "6" }],
    ["path", { d: "M15.5 8.3a6 6 0 1 1-7.2 7.2" }],
    ["path", { d: "M8 6.5h2v5" }]
]);
