// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Contact = createIcon("contact", [
    ["rect", { x: "3", y: "4", width: "18", height: "16", rx: "2.5" }],
    ["circle", { cx: "9", cy: "10", r: "2" }],
    ["path", { d: "M5.5 17a3.5 3.5 0 0 1 7 0" }],
    ["path", { d: "M15 10h3M15 14h3" }]
]);
