// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Copy = /* @__PURE__ */ createIcon("copy", [
    ["path", { d: "M8 8V5a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-3" }],
    ["rect", { x: "3", y: "8", width: "13", height: "13", rx: "2.5" }]
]);
