// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Cpu = /* @__PURE__ */ createIcon("cpu", [
    ["rect", { x: "5", y: "5", width: "14", height: "14", rx: "2.5" }],
    ["rect", { x: "9", y: "9", width: "6", height: "6", rx: "1" }],
    ["path", { d: "M9 2.5V5M15 2.5V5M9 19v2.5M15 19v2.5M2.5 9H5M2.5 15H5M19 9h2.5M19 15h2.5" }]
]);
