// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const CreditCard = createIcon("credit-card", [
    ["rect", { x: "2.5", y: "5", width: "19", height: "14", rx: "2.5" }],
    ["path", { d: "M2.5 10h19M6 15h4" }]
]);
