// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Crop = /* @__PURE__ */ createIcon("crop", [
    ["path", { d: "M6 3v13a2 2 0 0 0 2 2h13" }],
    ["path", { d: "M3 8h13a2 2 0 0 1 2 2v11" }]
]);
