// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Dashboard = /* @__PURE__ */ createIcon("dashboard", [
    ["rect", { x: "3", y: "3", width: "10", height: "10", rx: "1" }],
    ["rect", { x: "16", y: "3", width: "5", height: "10", rx: "1" }],
    ["rect", { x: "16", y: "16", width: "5", height: "5", rx: "1" }],
    ["rect", { x: "3", y: "16", width: "10", height: "5", rx: "1" }]
]);
