// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Dice = createIcon("dice", [
    ["rect", { x: "3", y: "3", width: "18", height: "18", rx: "2.5" }],
    ["path", { d: "M8 8h.1M16 8h.1M12 12h.1M8 16h.1M16 16h.1" }]
]);
