// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Download = /* @__PURE__ */ createIcon("download", [
    ["path", { d: "M4 16v3a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-3" }],
    ["path", { d: "M12 4v11M7 10l5 5 5-5" }]
]);
