// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Drag = createIcon("drag", [
    ["path", { d: "M9 6h.1M9 12h.1M9 18h.1M15 6h.1M15 12h.1M15 18h.1" }]
]);
