// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Edit = /* @__PURE__ */ createIcon("edit", [
    ["path", { d: "M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4z" }],
    ["path", { d: "M13 20h7.5" }]
]);
