// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Eraser = createIcon("eraser", [
    ["path", { d: "M7 21l-4-4 11-11 6 6-9 9z" }],
    ["path", { d: "M5 19h16" }]
]);
