// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Eraser = createIcon("eraser", [
    ["path", { d: "M7 18l-3.5-3.5 10-10 6 6-8.5 8.5z" }],
    ["path", { d: "M9.5 8.5l6 6" }],
    ["path", { d: "M5 22h16" }]
]);
