// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const ErrorFilled = createIcon("error-filled", [
    ["path", { fill: "currentColor", "fill-rule": "evenodd", d: "M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zm-1 4h2v5h-2zm0 8h2v2h-2z" }]
]);
