// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Error = /* @__PURE__ */ createIcon("error", [
    ["circle", { cx: "12", cy: "12", r: "9" }],
    ["path", { d: "M12 8v5M12 16.5h.1" }]
]);
