// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Euro = /* @__PURE__ */ createIcon("euro", [
    ["path", { d: "M18 5.5A8 8 0 0 0 6 12a8 8 0 0 0 12 6.5" }],
    ["path", { d: "M3.5 10h11M3.5 14h11" }]
]);
