// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const ExternalLink = /* @__PURE__ */ createIcon("external-link", [
    ["path", { d: "M20 10v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h8" }],
    ["path", { d: "M14 4h6v6M20 4l-9 9" }]
]);
