// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Eye = createIcon("eye", [
    ["path", { d: "M2.5 12c2.5-5 6-7.5 9.5-7.5s7 2.5 9.5 7.5c-2.5 5-6 7.5-9.5 7.5S5 17 2.5 12z" }],
    ["circle", { cx: "12", cy: "12", r: "3" }]
]);
