// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const FileCheck = createIcon("file-check", [
    ["path", { d: "M14 3H6v18h12V7z" }],
    ["path", { d: "M14 3v4h4" }],
    ["path", { d: "M9 15l2 2 4-4" }]
]);
