// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const File = /* @__PURE__ */ createIcon("file", [
    ["path", { d: "M14 3H6v18h12V7z" }],
    ["path", { d: "M14 3v4h4" }],
    ["path", { d: "M9 13h6M9 17h6" }]
]);
