// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const FileWarning = createIcon("file-warning", [
    ["path", { d: "M14 3H6v18h12V7z" }],
    ["path", { d: "M14 3v4h4" }],
    ["path", { d: "M12 11v4" }],
    ["path", { d: "M12 18h.1" }]
]);
