// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const FileSpreadsheet = /* @__PURE__ */ createIcon("file-spreadsheet", [
    ["path", { d: "M14 3H6v18h12V7z" }],
    ["path", { d: "M14 3v4h4" }],
    ["path", { d: "M9 12h6M9 16h6M12 12v6" }]
]);
