// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const FileDown = createIcon("file-down", [
    ["path", { d: "M14 3H6v18h12V7z" }],
    ["path", { d: "M14 3v4h4" }],
    ["path", { d: "M12 11v7" }],
    ["path", { d: "M9.5 15.5L12 18l2.5-2.5" }]
]);
