// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const FileSpreadsheet = createIcon("file-spreadsheet", [
    ["path", { d: "M14 3H6v18h12V7z" }],
    ["path", { d: "M14 3v4h4" }],
    ["path", { d: "M8 12h8M8 16h8M12 12v6" }]
]);
