// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const FileCode = createIcon("file-code", [
    ["path", { d: "M14 3H6v18h12V7z" }],
    ["path", { d: "M14 3v4h4" }],
    ["path", { d: "M11 13l-2 2 2 2M13 13l2 2-2 2" }]
]);
