// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Fingerprint = createIcon("fingerprint", [
    ["path", { d: "M21.5 13A9.5 9.5 0 1 1 12 3.5" }],
    ["path", { d: "M12 19A6 6 0 1 1 18 13" }],
    ["path", { d: "M9.5 13A2.5 2.5 0 1 1 12 15.5" }]
]);
