// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Fingerprint = createIcon("fingerprint", [
    ["path", { d: "M4.5 16a7.5 7.5 0 0 1 15 0" }],
    ["path", { d: "M4.5 16v3M19.5 16v3" }],
    ["path", { d: "M7.5 16a4.5 4.5 0 0 1 9 0" }],
    ["path", { d: "M7.5 16v3.5M16.5 16v3.5" }],
    ["path", { d: "M12 14.5v6" }]
]);
