// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Flag = /* @__PURE__ */ createIcon("flag", [
    ["path", { d: "M5 21V4" }],
    ["path", { d: "M5 4h13l-3 4 3 4H5" }]
]);
