// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Flask = createIcon("flask", [
    ["path", { d: "M9 3h6" }],
    ["path", { d: "M10 3v6l-6 9a1.5 1.5 0 0 0 1.3 2.3h13.4A1.5 1.5 0 0 0 20 18l-6-9V3" }],
    ["path", { d: "M7 15h10" }]
]);
