// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const FolderTree = createIcon("folder-tree", [
    ["path", { d: "M6 4v14M6 9h6M6 18h6" }],
    ["rect", { x: "12", y: "6", width: "8", height: "6", rx: "2.5" }],
    ["rect", { x: "12", y: "15", width: "8", height: "6", rx: "2.5" }]
]);
