// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const FolderTree = createIcon("folder-tree", [
    ["path", { d: "M6 4v14M6 9h4M6 18h4" }],
    ["rect", { x: "11", y: "6", width: "10", height: "6", rx: "2.5" }],
    ["rect", { x: "11", y: "15", width: "10", height: "6", rx: "2.5" }]
]);
