// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Fullscreen = /* @__PURE__ */ createIcon("fullscreen", [
    ["path", { d: "M4 8V4H8M20 8V4H16M4 16V20H8M20 16V20H16" }]
]);
