// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const FullscreenExit = createIcon("fullscreen-exit", [
    ["path", { d: "M9 5V9H5M15 5V9H19M9 19V15H5M15 19V15H19" }]
]);
