// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const HandCoins = /* @__PURE__ */ createIcon("hand-coins", [
    ["path", { d: "M7 9h10v10a2 2 0 0 1-2 2H9a2 2 0 0 1-2-2z" }],
    ["path", { d: "M9 5h6v4H9z" }],
    ["circle", { cx: "12", cy: "15", r: "2" }]
]);
