// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Hash = /* @__PURE__ */ createIcon("hash", [
    ["path", { d: "M5 9h14M5 15h14M10 4l-2 16M16 4l-2 16" }]
]);
