// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const History = createIcon("history", [
    ["path", { d: "M3 12A9 9 0 1 1 12 21" }],
    ["path", { d: "M3 8v4h4" }],
    ["path", { d: "M12 8v4l3 2" }]
]);
