// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const ImageOff = /* @__PURE__ */ createIcon("image-off", [
    ["rect", { x: "3", y: "3", width: "18", height: "18", rx: "2.5" }],
    ["path", { d: "M21 15l-5-5-9 9" }],
    ["path", { d: "M4 4l16 16" }]
]);
