// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const ImagePlus = createIcon("image-plus", [
    ["path", { d: "M17 3H3v18h18V9" }],
    ["path", { d: "M15 6h6M18 3v6" }]
]);
