// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Inbox = createIcon("inbox", [
    ["path", { d: "M3 13l3-8h12l3 8v6H3z" }],
    ["path", { d: "M3 13h5l1.5 3h5L16 13h5" }]
]);
