// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Info = /* @__PURE__ */ createIcon("info", [
    ["circle", { cx: "12", cy: "12", r: "9" }],
    ["path", { d: "M12 11v5M12 8h.1" }]
]);
