// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const InfoFilled = createIcon("info-filled", [
    ["path", { fill: "currentColor", "fill-rule": "evenodd", d: "M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zm-1 5h2v2h-2zm0 4h2v5h-2z" }]
], { filled: true });
