// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Key = createIcon("key", [
    ["circle", { cx: "8", cy: "16", r: "4.5" }],
    ["path", { d: "M11.2 12.8L20 4M17 7l2.5 2.5M14.5 9.5L17 12" }]
]);
