// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Keyboard = createIcon("keyboard", [
    ["rect", { x: "2.5", y: "6", width: "19", height: "12", rx: "2.5" }],
    ["path", { d: "M6 10h.1M10 10h.1M14 10h.1M18 10h.1" }],
    ["path", { d: "M6 14h.1M18 14h.1" }],
    ["path", { d: "M9 14h6" }]
]);
