// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const KeyboardHide = createIcon("keyboard-hide", [
    ["rect", { x: "2.5", y: "4", width: "19", height: "12", rx: "2.5" }],
    ["path", { d: "M6 8h.1M10 8h.1M14 8h.1M18 8h.1" }],
    ["path", { d: "M6 12h.1M18 12h.1" }],
    ["path", { d: "M9 12h6" }],
    ["path", { d: "M9 18l3 3 3-3" }]
]);
