// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Landmark = createIcon("landmark", [
    ["path", { d: "M3 9l9-5 9 5" }],
    ["path", { d: "M3 21h18M5 18h14" }],
    ["path", { d: "M6 9v9M10 9v9M14 9v9M18 9v9" }]
]);
