// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Layers = /* @__PURE__ */ createIcon("layers", [
    ["path", { d: "M12 3l9 5-9 5-9-5z" }],
    ["path", { d: "M3 12l9 5 9-5" }],
    ["path", { d: "M3 16l9 5 9-5" }]
]);
