// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Link = createIcon("link", [
    ["path", { d: "M9 15l6-6" }],
    ["path", { d: "M11 6.5l1.5-1.5a3.5 3.5 0 0 1 5 5L16 11.5" }],
    ["path", { d: "M13 17.5l-1.5 1.5a3.5 3.5 0 0 1-5-5L8 12.5" }]
]);
