// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Lock = /* @__PURE__ */ createIcon("lock", [
    ["rect", { x: "4", y: "11", width: "16", height: "10", rx: "2.5" }],
    ["path", { d: "M8 11V7a4 4 0 0 1 8 0v4" }]
]);
