// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const LogIn = /* @__PURE__ */ createIcon("log-in", [
    ["path", { d: "M14 4h5a1.5 1.5 0 0 1 1.5 1.5v13A1.5 1.5 0 0 1 19 20h-5" }],
    ["path", { d: "M3 12h11M10 8l4 4-4 4" }]
]);
