// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const LogOut = createIcon("log-out", [
    ["path", { d: "M10 4H5a1.5 1.5 0 0 0 -1.5 1.5v13A1.5 1.5 0 0 0 5 20h5" }],
    ["path", { d: "M10 12h11M17 8l4 4-4 4" }]
]);
