// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Mail = createIcon("mail", [
    ["rect", { x: "2.5", y: "5", width: "19", height: "14", rx: "2.5" }],
    ["path", { d: "M2.5 8l9.5 6.5L21.5 8" }]
]);
