// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const MapPin = /* @__PURE__ */ createIcon("map-pin", [
    ["path", { d: "M12 21s-7-6-7-11.5a7 7 0 0 1 14 0C19 15 12 21 12 21z" }],
    ["circle", { cx: "12", cy: "9.5", r: "2.5" }]
]);
