// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Message = /* @__PURE__ */ createIcon("message", [
    ["path", { d: "M21 12a8 8 0 0 1-11.6 7.2L3 21l1.8-5.4A8 8 0 1 1 21 12z" }],
    ["path", { d: "M8.5 10.5h7M8.5 13.5h4" }]
]);
