// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const MinusCircle = /* @__PURE__ */ createIcon("minus-circle", [
    ["circle", { cx: "12", cy: "12", r: "9" }],
    ["path", { d: "M8 12h8" }]
]);
