// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Monitor = /* @__PURE__ */ createIcon("monitor", [
    ["rect", { x: "2.5", y: "4", width: "19", height: "13", rx: "2.5" }],
    ["path", { d: "M12 17v4M8 21h8" }]
]);
