// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Moon = /* @__PURE__ */ createIcon("moon", [
    ["path", { d: "M20 14.5A8.5 8.5 0 1 1 9.5 4a7 7 0 0 0 10.5 10.5z" }]
]);
