// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const More = /* @__PURE__ */ createIcon("more", [
    ["path", { d: "M12 6h.1M12 12h.1M12 18h.1" }]
]);
