// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Network = createIcon("network", [
    ["rect", { x: "9", y: "3", width: "6", height: "5", rx: "1" }],
    ["rect", { x: "3", y: "16", width: "6", height: "5", rx: "2.5" }],
    ["rect", { x: "15", y: "16", width: "6", height: "5", rx: "2.5" }],
    ["path", { d: "M12 8v4M6 16v-4h12v4" }]
]);
