// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Numpad = /* @__PURE__ */ createIcon("numpad", [
    ["path", { d: "M7 7h.1M12 7h.1M17 7h.1M7 12h.1M12 12h.1M17 12h.1M7 17h.1M12 17h.1M17 17h.1" }]
]);
