// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const PackagePlus = createIcon("package-plus", [
    ["path", { d: "M12 3L3.5 7.5L3.5 16.5L12 21L20.5 16.5L20.5 9" }],
    ["path", { d: "M3.5 7.5L12 12M12 12v9" }],
    ["path", { d: "M16 3v6M13 6h6" }]
]);
