// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Package = /* @__PURE__ */ createIcon("package", [
    ["path", { d: "M12 3l8.5 4.5v9L12 21l-8.5-4.5v-9z" }],
    ["path", { d: "M3.5 7.5L12 12l8.5-4.5M12 12v9" }]
]);
