// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const PaperRoll = /* @__PURE__ */ createIcon("paper-roll", [
    ["circle", { cx: "8", cy: "9", r: "5" }],
    ["path", { d: "M13 9v9h8" }],
    ["path", { d: "M8 9h.1" }]
]);
