// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Paperclip = /* @__PURE__ */ createIcon("paperclip", [
    ["path", { d: "M21 11.1l-9 9a5.5 5.5 0 0 1-8-8l9-9a3.5 3.5 0 0 1 5 5l-9 9a1.5 1.5 0 0 1-2-2l8.5-8.5" }]
]);
