// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Percent = /* @__PURE__ */ createIcon("percent", [
    ["path", { d: "M19 5L5 19" }],
    ["circle", { cx: "7", cy: "7", r: "2.5" }],
    ["circle", { cx: "17", cy: "17", r: "2.5" }]
]);
