// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Phone = createIcon("phone", [
    ["path", { d: "M5 3h4l2 5-2.5 1.5a11 11 0 0 0 6 6L16 13l5 2v4a2 2 0 0 1-2 2A16 16 0 0 1 3 5a2 2 0 0 1 2-2z" }]
]);
