// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const PlusCircle = /* @__PURE__ */ createIcon("plus-circle", [
    ["circle", { cx: "12", cy: "12", r: "9" }],
    ["path", { d: "M12 8v8M8 12h8" }]
]);
