// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Pos = createIcon("pos", [
    ["rect", { x: "4", y: "3", width: "16", height: "18", rx: "2.5" }],
    ["rect", { x: "7", y: "6", width: "10", height: "5", rx: "1" }],
    ["path", { d: "M8 15h.1M12 15h.1M16 15h.1M8 18h.1M12 18h.1M16 18h.1" }]
]);
