// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const PowerOff = /* @__PURE__ */ createIcon("power-off", [
    ["path", { d: "M18.4 6.2a9 9 0 1 1-12.8 0" }],
    ["path", { d: "M12 2.6v9" }]
]);
