// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Print = /* @__PURE__ */ createIcon("print", [
    ["path", { d: "M7 9V4h10v5" }],
    ["rect", { x: "3", y: "9", width: "18", height: "8", rx: "2.5" }],
    ["path", { d: "M7 13.5h10V20H7z" }]
]);
