// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const QrCode = /* @__PURE__ */ createIcon("qr-code", [
    ["rect", { x: "3", y: "3", width: "7", height: "7", rx: "1" }],
    ["rect", { x: "14", y: "3", width: "7", height: "7", rx: "1" }],
    ["rect", { x: "3", y: "14", width: "7", height: "7", rx: "1" }],
    ["path", { d: "M14 14h3v3h-3zM21 14v3M14 21h3M21 21h.1" }]
]);
