// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Radar = createIcon("radar", [
    ["path", { d: "M12 4a9 9 0 1 1-9 9" }],
    ["path", { d: "M12 7a6 6 0 1 1-6 6" }],
    ["path", { d: "M12 10a3 3 0 1 1-3 3" }],
    ["path", { d: "M12 13L19 6" }]
]);
