// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const ReceiptVoid = /* @__PURE__ */ createIcon("receipt-void", [
    ["path", { d: "M6 3h12v18l-2-1.5-2 1.5-2-1.5-2 1.5-2-1.5-2 1.5z" }],
    ["path", { d: "M9.5 8.5l5 5M14.5 8.5l-5 5" }]
]);
