// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const ReceiptFilled = /* @__PURE__ */ createIcon("receipt-filled", [
    ["path", { fill: "currentColor", "fill-rule": "evenodd", d: "M6 3h12v18l-2-1.5-2 1.5-2-1.5-2 1.5-2-1.5-2 1.5zM9 7h6v2h-6zM9 11h6v2h-6zM9 15h3v2h-3z" }]
], { filled: true });
