// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Receipt = createIcon("receipt", [
    ["path", { d: "M6 3h12v18l-2-1.5-2 1.5-2-1.5-2 1.5-2-1.5-2 1.5z" }],
    ["path", { d: "M9 8h6M9 12h6M9 16h3" }]
]);
