// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const ReceiptText = createIcon("receipt-text", [
    ["path", { d: "M6 3h12v18l-2-1.5-2 1.5-2-1.5-2 1.5-2-1.5-2 1.5z" }],
    ["path", { d: "M9 7h6M9 10h6M9 13h6M9 16h4" }]
]);
