// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Redo = /* @__PURE__ */ createIcon("redo", [
    ["path", { d: "M16 8H20V4" }],
    ["path", { d: "M20 8c-3-4-8-5-12-2a7 7 0 0 0 0 12" }]
]);
