// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Refresh = /* @__PURE__ */ createIcon("refresh", [
    ["path", { d: "M4 12a8 8 0 0 1 14-4" }],
    ["path", { d: "M22 5v4h-4" }],
    ["path", { d: "M20 12a8 8 0 0 1-14 4" }],
    ["path", { d: "M2 19v-4h4" }]
]);
