// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Repeat = /* @__PURE__ */ createIcon("repeat", [
    ["path", { d: "M17 3l4 4-4 4M3 11V9a2 2 0 0 1 2-2h16M7 21l-4-4 4-4M21 13v2a2 2 0 0 1-2 2H3" }]
]);
