// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Reset = /* @__PURE__ */ createIcon("reset", [
    ["path", { d: "M3 12a9 9 0 1 0 2.6-6.4L3 8" }],
    ["path", { d: "M3 3.5V8h4.5" }]
]);
