// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Save = /* @__PURE__ */ createIcon("save", [
    ["path", { d: "M4 4h13l3 3v13H4z" }],
    ["path", { d: "M8 4v5h7V4" }],
    ["path", { d: "M7 20v-6h10v6" }]
]);
