// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Send = createIcon("send", [
    ["path", { d: "M21 3L3 10l8 2 2 8z" }],
    ["path", { d: "M11 12l10-9" }]
]);
