// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Settings = /* @__PURE__ */ createIcon("settings", [
    ["path", { d: "M4 7h16M4 17h16" }],
    ["circle", { cx: "9", cy: "7", r: "2.5" }],
    ["circle", { cx: "15", cy: "17", r: "2.5" }]
]);
