// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const ShieldCheck = /* @__PURE__ */ createIcon("shield-check", [
    ["path", { d: "M12 3l8 3v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6z" }],
    ["path", { d: "M8 12.5l2.5 2.5L16 9.5" }]
]);
