// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const ShieldQuestion = /* @__PURE__ */ createIcon("shield-question", [
    ["path", { d: "M12 3l8 3v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6z" }],
    ["path", { d: "M10 9.5a2 2 0 1 1 2.5 2c-.5.2-.5.7-.5 1.2M12 16h.1" }]
]);
