// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const ShieldX = /* @__PURE__ */ createIcon("shield-x", [
    ["path", { d: "M12 3l8 3v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6z" }],
    ["path", { d: "M9 9l6 6M15 9l-6 6" }]
]);
