// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const ShoppingCart = /* @__PURE__ */ createIcon("shopping-cart", [
    ["path", { d: "M3 4h2l2.5 11h11l2-7H7" }],
    ["circle", { cx: "9", cy: "20", r: "1.5" }],
    ["circle", { cx: "18", cy: "20", r: "1.5" }]
]);
