// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const SignatureUnit = /* @__PURE__ */ createIcon("signature-unit", [
    ["rect", { x: "3", y: "5", width: "18", height: "14", rx: "2.5" }],
    ["rect", { x: "6", y: "9", width: "5", height: "4", rx: "1" }],
    ["path", { d: "M14 10h4M14 14h4" }]
]);
