// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Sparkles = createIcon("sparkles", [
    ["path", { d: "M12 4l1.8 5.2L19 11l-5.2 1.8L12 18l-1.8-5.2L5 11l5.2-1.8z" }],
    ["path", { d: "M19 17l.6 1.4L21 19l-1.4.6L19 21l-.6-1.4L17 19l1.4-.6z" }]
]);
