// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Sun = createIcon("sun", [
    ["circle", { cx: "12", cy: "12", r: "3.5" }],
    ["path", { d: "M12 5.5V3M12 18.5V21M18.5 12H21M5.5 12H3M16.6 7.4L18.4 5.6M7.4 7.4L5.6 5.6M16.6 16.6L18.4 18.4M7.4 16.6L5.6 18.4" }]
]);
