// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Tag = /* @__PURE__ */ createIcon("tag", [
    ["path", { d: "M20.5 12.5l-8 8L3 11V3h8l9.5 9.5z" }],
    ["circle", { cx: "7", cy: "7", r: "1.5" }]
]);
