// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Timer = createIcon("timer", [
    ["circle", { cx: "12", cy: "13.5", r: "7.5" }],
    ["path", { d: "M10 2.5h4" }],
    ["path", { d: "M12 13.5V9" }]
]);
