// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Trash = createIcon("trash", [
    ["path", { d: "M5 7h14M9 7V4h6v3M6 7l1 13h10l1-13" }],
    ["path", { d: "M10 11v6M14 11v6" }]
]);
