// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const TrendingDown = /* @__PURE__ */ createIcon("trending-down", [
    ["path", { d: "M3 7l6 6 4-4 8 8" }],
    ["path", { d: "M15 17h6v-6" }]
]);
