// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const TrendingUp = /* @__PURE__ */ createIcon("trending-up", [
    ["path", { d: "M3 17l6-6 4 4 8-8" }],
    ["path", { d: "M15 7h6v6" }]
]);
