// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Undo = createIcon("undo", [
    ["path", { d: "M8 8H4V4" }],
    ["path", { d: "M4 8c3-4 8-5 12-2a7 7 0 0 1 0 12" }]
]);
