// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const User = createIcon("user", [
    ["circle", { cx: "12", cy: "8", r: "4" }],
    ["path", { d: "M4 21a8 8 0 0 1 16 0" }]
]);
