// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const UserFilled = createIcon("user-filled", [
    ["path", { fill: "currentColor", d: "M8 8A4 4 0 1 1 16 8A4 4 0 1 1 8 8ZM4 21A8 8 0 0 1 20 21Z" }]
], { filled: true });
