// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Users = /* @__PURE__ */ createIcon("users", [
    ["circle", { cx: "9", cy: "8", r: "4" }],
    ["path", { d: "M2.5 21a6.5 6.5 0 0 1 13 0" }],
    ["path", { d: "M16 4a4 4 0 0 1 0 8" }],
    ["path", { d: "M21 21a6 6 0 0 0 -3.5 -5.5" }]
]);
