// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const UserPlus = /* @__PURE__ */ createIcon("user-plus", [
    ["circle", { cx: "9", cy: "8", r: "4" }],
    ["path", { d: "M2.5 21a6.5 6.5 0 0 1 13 0" }],
    ["path", { d: "M16 10H22M19 7V13" }]
]);
