// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const UserFilled = createIcon("user-filled", [
    ["circle", { cx: "12", cy: "8", r: "4", fill: "currentColor" }],
    ["path", { fill: "currentColor", d: "M4 21a8 8 0 0 1 16 0z" }]
], { filled: true });
