// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Wallet = /* @__PURE__ */ createIcon("wallet", [
    ["path", { d: "M3 7a2 2 0 0 1 2-2h14v4M3 7v11a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V9H5a2 2 0 0 1-2-2" }],
    ["path", { d: "M17 14h.1" }]
]);
