// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Wand = /* @__PURE__ */ createIcon("wand", [
    ["path", { d: "M4 20L15 9l2 2" }],
    ["path", { d: "M18 2v2M18 6v2M15 5h2M19 5h2" }]
]);
