// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Warning = createIcon("warning", [
    ["path", { d: "M12 3.5l9.5 16.5h-19z" }],
    ["path", { d: "M12 10v4M12 17.5h.1" }]
]);
