// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const Wifi = /* @__PURE__ */ createIcon("wifi", [
    ["path", { d: "M8.5 17A4 4 0 0 1 15.5 17" }],
    ["path", { d: "M5.5 15.3A7.5 7.5 0 0 1 18.5 15.3" }],
    ["path", { d: "M2.5 13.5A11 11 0 0 1 21.5 13.5" }],
    ["path", { d: "M12 19h.1" }]
]);
