// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const X = /* @__PURE__ */ createIcon("x", [
    ["path", { d: "M6.5 6.5l11 11M17.5 6.5l-11 11" }]
]);
