// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const XCircleFilled = createIcon("x-circle-filled", [
    ["path", { fill: "currentColor", "fill-rule": "evenodd", d: "M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zM9 9L12 10.6 15 9 13.4 12 15 15 12 13.4 9 15 10.6 12z" }]
], { filled: true });
