// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const XCircleFilled = createIcon("x-circle-filled", [
    ["path", { fill: "currentColor", "fill-rule": "evenodd", d: "M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zM8.3 9.7L10.6 12 8.3 14.3 9.7 15.7 12 13.4 14.3 15.7 15.7 14.3 13.4 12 15.7 9.7 14.3 8.3 12 10.6 9.7 8.3z" }]
], { filled: true });
