// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const XCircle = createIcon("x-circle", [
    ["circle", { cx: "12", cy: "12", r: "9" }],
    ["path", { d: "M9 9l6 6M15 9l-6 6" }]
]);
