// Generated by tools/build.mjs. Do not edit.
import { createIcon } from "./create-icon.js";

export const ZoomOut = createIcon("zoom-out", [
    ["circle", { cx: "10.5", cy: "10.5", r: "6" }],
    ["path", { d: "M15 15l5.5 5.5" }],
    ["path", { d: "M7.5 10.5h6" }]
]);
