import { describe, it, expect } from "vitest";
import { emitIconsDart } from "./emit-icons-dart.mjs";

const model = { order: ["arrow-left", "cash-drawer"], icons: {
  "arrow-left": { group: "navigation", de: "Zurück", terms: [], filled: false, stroke: [{ tag: "path", attrs: { d: "M14 6l-6 6 6 6" } }] },
  "cash-drawer": { group: "cash", de: "Kassenlade", terms: [], filled: true,
    stroke: [{ tag: "rect", attrs: { x: "3", y: "10", width: "18", height: "10" } }],
    fill: [{ tag: "rect", attrs: { x: "3", y: "10", width: "18", height: "10", fill: "currentColor" } }] },
} };

describe("emitIconsDart", () => {
  const out = emitIconsDart(model);
  it("names constants in lowerCamel and adds Filled variants", () => {
    expect(out).toContain("static const KdIconData arrowLeft = KdIconData(stroke: [");
    expect(out).toContain("static const KdIconData cashDrawer = KdIconData(stroke: [");
    expect(out).toContain("static const KdIconData cashDrawerFilled = KdIconData(fill: [");
  });
  it("writes absolute ops with rounded corners applied", () => {
    expect(out).toContain("KdMove(14, 6), KdLine(8, 12), KdLine(14, 18)");
    expect(out).toMatch(/cashDrawer = KdIconData\(stroke: \[KdMove\(5\.5, 10\), KdLine\(18\.5, 10\), KdCubic\(/);
  });
  it("exposes a byName map in index order", () => {
    expect(out).toContain("'arrow-left': arrowLeft,");
    expect(out).toContain("'cash-drawer-filled': cashDrawerFilled,");
    expect(out.indexOf("'arrow-left'")).toBeLessThan(out.indexOf("'cash-drawer'"));
  });
  it("starts with the generated-file notice and no imports beyond icon.dart", () => {
    expect(out.startsWith("// Generated by tools/build.mjs. Do not edit.")).toBe(true);
    expect(out).toContain("import 'icon.dart';");
  });
});
