/** The faces the packages ship. Kept in one place so Dart and the web agree. */
export const WEB_FACES = [
  { family: "Archivo", weight: 400, file: "Archivo-400.woff2" },
  { family: "Archivo", weight: 500, file: "Archivo-500.woff2" },
  { family: "Archivo", weight: 600, file: "Archivo-600.woff2" },
  { family: "Archivo", weight: 700, file: "Archivo-700.woff2" },
  { family: "DM Mono", weight: 400, file: "DMMono-400.woff2" },
  { family: "DM Mono", weight: 500, file: "DMMono-500.woff2" },
];

/**
 * Self-hosted faces: no third-party request, so a consumer needs no cookie
 * banner for a font. `swap` keeps text readable while the file loads.
 */
export function emitFontsCss() {
  const faces = WEB_FACES.map(
    (f) => `@font-face {
  font-family: "${f.family}";
  src: url("./fonts/${f.file}") format("woff2");
  font-weight: ${f.weight};
  font-style: normal;
  font-display: swap;
}`,
  ).join("\n\n");
  return `/* Generated by tools/build.mjs. Do not edit. */\n\n${faces}\n`;
}
